name: Deploy to Firebase Preview
on:
  #TODO remove push when we are ready to merge
  push:
    branches:
      - firebase
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: write
jobs:
  build_and_preview:
    uses: ./.github/workflows/common-firebase-deploy.yml
    secrets: inherit
