name: Deploy to Firebase PROD
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    uses: ./.github/workflows/common-firebase-deploy.yml
    secrets: inherit
    with:
      is_production: true
