name: Deploy to Firebase PROD
on:
  push:
    branches:
      - main
      - firebase #TODO remove when we are ready to merge
jobs:
  build_and_deploy:
    uses: ./.github/workflows/common-firebase-deploy.yml
    secrets: inherit
    with:
      channelId: live
